version: '3.7'
services:
  web:
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: websrvr
    #restart: always
    volumes:
      - /app/node_modules     
      - .:/app
    ports:
      - "3000:3000"
